author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /Hadriani-2020-02-06
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://iiif.archivelab.org/iiif//81285178.4931.emory.edu$1/full/full/0/default.jpg
image_size:
  page:
    height: 1496
    width: 2325
permalink: pretty
publication_info:
  date: '2020'
  editors: []
  title: 'Hadriani Iunii medici Emblemata, ad D. Arnoldum Cobelium : eiusdem Aenigmatum
    libellus, ad D. Arnoldum Rosenbergum'
show_annotation_author: true
source_info:
  title: 'Hadriani Iunii medici Emblemata, ad D. Arnoldum Cobelium : eiusdem Aenigmatum
    libellus, ad D. Arnoldum Rosenbergum'
  via_readux: true
tagline: an annotated digital edition
title: 'Hadriani Iunii medici Emblemata, ad D. Arnoldum Cobelium : eiusdem Aenigmatum
  libellus, ad D. Arnoldum Rosenbergum'
url: https://sarepal.github.io
version: 0.7
